-- ********** CREATE REALTOR MONTHLY INVENTORY & BASE DATA **********
-- DROP TABLE dbo.REALTOR_MNTHLY_METRO;

CREATE TABLE dbo.REALTOR_MNTHLY_METRO (
    month_date_yyyymm INT,
	cbsa_code INT,
	cbsa_title VARCHAR(75),
	HouseholdRank INT,
    median_listing_price INT,
    active_listing_count INT,
    median_days_on_market INT,
    new_listing_count INT,
    price_increased_count INT,
    price_reduced_count INT,
    pending_listing_count INT,
    median_listing_price_per_square_foot INT,
    median_square_feet INT,
    average_listing_price INT,
    total_listing_count INT,
    pending_ratio FLOAT,
    quality_flag INT,
    median_listing_price_ly INT,
    active_listing_count_ly INT,
    median_days_on_market_ly INT,
    new_listing_count_ly INT,
    price_increased_count_ly INT,
    price_reduced_count_ly INT,
    pending_listing_count_ly INT,
    median_listing_price_per_square_foot_ly INT,
    median_square_feet_ly INT,
    average_listing_price_ly INT,
    total_listing_count_ly INT,
    pending_ratio_ly FLOAT,
    median_listing_price_lm INT,
    active_listing_count_lm INT,
    median_days_on_market_lm INT,
    new_listing_count_lm INT,
    price_increased_count_lm INT,
    price_reduced_count_lm INT,
    pending_listing_count_lm INT,
    median_listing_price_per_square_foot_lm INT,
    median_square_feet_lm INT,
    average_listing_price_lm INT,
    total_listing_count_lm INT,
    pending_ratio_lm FLOAT,
	Update_Date DATETIME
);
