CREATE VIEW dbo.LKP_ZW_ZIP_lOCATION AS
SELECT DISTINCT RegionID, State, City, Metro, CountyName, Zip_Code
FROM dbo.LKP_ZW_ZIP_lOCATION_ARCHIVE;

-- ******** QA IF NOT UNIQUE ********
SELECT RegionID, COUNT(*) AS COUNT_ROWS
FROM dbo.LKP_ZW_ZIP_lOCATION
GROUP BY RegionID
ORDER BY COUNT(*) DESC