
DROP TABLE dbo.LKP_ZW_ZIP_lOCATION_ARCHIVE;

-- CREATE ZW HOME VALUE LOOKUP TABLE 

CREATE TABLE dbo.LKP_ZW_ZIP_lOCATION_ARCHIVE (
RegionID INT,
State VARCHAR(255),
City VARCHAR(255),
Metro VARCHAR(255),
CountyName VARCHAR(255),
Zip_Code VARCHAR(5),
Dataset_Type VARCHAR(50),
Report_Date DATE
)

SELECT * FROM dbo.LKP_ZW_ZIP_lOCATION_ARCHIVE;

SELECT Zip_Code, COUNT(*) AS COUNTROW
FROM dbo.LKP_ZW_ZIP_lOCATION_ARCHIVE
GROUP BY Zip_Code
ORDER BY 2 DESC;

SELECT DISTINCT 
RegionID,
State,
City,
Metro,
CountyName,
Zip_Code
FROM dbo.LKP_ZW_ZIP_lOCATION_ARCHIVE